name: Process Data from Private Repo

# Trigger this workflow manually or through a dispatch event
on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_all_shoes]

jobs:
  process-and-sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the public repository (it will serve as the execution context)
      - name: Checkout Public Repo
        uses: actions/checkout@v3

      # Step 2: Clone the private repository into a separate folder
      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.PROFILE_URL }}:${{secrets.PUBLIC_PAT}}@github.com/${{ secrets.PROFILE_URL }}/supplier2_women_shoes_private.git private_repo

      - name: Set up environment and run script with secrets
        run: |
            echo "Setting up environment variables"
        env:
            API_KEY: ${{ secrets.API_KEY }}
            API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}

      - name: Install Node.js dependencies 
        run: npm install axios csv-parser dotenv shopify-api-node fs
          
      - name: Update all products
        run: node /home/runner/work/supplier2-women-shoes-update-all/supplier2-women-shoes-update-all/update_products.js
        env:
            SHOP: ${{ secrets.SHOP }}
            SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}